name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Black Code Formatter
      run:  lgeiger/black-action@v1.0.1
    - name: Mypy Check
      run: jpetrucciani/mypy-check@0.730
