name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - run: sudo apt-get update
      - run: sudo apt-get upgrade
      - run: sudo apt-get install build-essential
      - uses: actions/checkout@v1
      - name: Black Code Formatter
        uses: lgeiger/black-action@v1.0.1
      - name: Mypy Check
        uses: jpetrucciani/mypy-check@0.730
